package constant;

public enum SensorEventType {
    CLIMATE_SENSOR_EVENT,
    LIGHT_SENSOR_EVENT,
    MOTION_SENSOR_EVENT,
    SWITCH_SENSOR_EVENT,
    TEMPERATURE_SENSOR_EVENT,
    DEVICE_ADDED_EVENT,
    DEVICE_REMOVED_EVENT,
    SCENARIO_ADDED_EVENT,
    SCENARIO_REMOVED_EVENT,
}
